
BOOST_DIR := /home/dgleich/dev/lib/boost_1_34_1
YASMIC_DIR := /home/dgleich/dev/yasmic

CXXFLAGS := $(CXXFLAGS) -I../ -I$(BOOST_DIR) -I$(YASMIC_DIR) 

all : simple_prop_map_test_4 simple_prop_map_test_3 simple_prop_map_test_2 simple_prop_map_test property_map_test
