PLATFORM ?= $(shell uname | tr A-Z a-z)
ARCH ?= $(shell getconf LONG_BIT)

-include Makefile-$(PLATFORM)-$(ARCH)-conf.inc

TOP_MAKEFILE_DIR:=$(dir $(lastword $(MAKEFILE_LIST)))

YASMIC_DIR=$(TOP_MAKEFILE_DIR)
LIBDIR=$(TOP_MAKEFILE_DIR)
LIBNAME=libmbgl-$(PLATFORM)-$(ARCH)

CXXFILES=components.cc max_flow.cc orderings.cc searches.cc shortest_path.cc spanning_trees.cc statistics.cc  structure.cc orderings.cc planar.cc layouts.cc
OBJFILES=$(patsubst %.cc,%.o,$(CXXFILES))

